lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # required for token verification
    pass_phrase: '%env(JWT_PASSPHRASE)%' # required for token creation
    token_ttl: 3600 # in seconds, default is 3600

# HTTP Only cookie - copied from github docs
    token_extractors:
        # from OverSeas Media http only cookie
        authorization_header:
            enabled: true
            prefix: BEARER
            name: Authorization
        # END from OverSeas Media http only cookie
        cookie:
            enabled: true
            name: BEARER
    set_cookies:
        #BEARER: ~

    #Full config with defaults:
        BEARER:
            lifetime: null #(defaults to token ttl)
            samesite: none
            path: /api/
            domain: null #(null means automatically set by symfony)
            secure: true #(default to true)
            httpOnly: true